#ifndef _NETWORKCOMMON_H_
#define _NETWORKCOMMON_H_
#pragma once

#include <MessageIdentifiers.h>

enum NetworkPacketIds
{
	MSG_DEFAULT = ID_USER_PACKET_ENUM,

	// SERVER PACKET
	MSG_GAMEOBJECT,
	
	// GAME OBJECT MANAGER PACKETS
	MSG_GAMEOBJECT_COMPONENT,
	MSG_GAMEOBJECT_DESTROY,

	// USER or GAME PACKETS
	MSG_GAME_PACKET_ENUM,

	// MOUSE_POSITION PACKET
	MSG_MOUSE_POSITION
};

#endif

